language: elixir
elixir:
  - 1.0.5
  - 1.1.1
otp_release:
  - 17.5
script:
  - MIX_ENV=test mix test --no-start --trace
after_script:
  - MIX_ENV=test mix coveralls.travis --no-start
services:
  - redis-server
sudo: false
